version: '3.1'

services:

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: angular_chat
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  angular-chat-server:
    image: marvin/angular_chat_server:latest
    container_name: angular_chat_server
    restart: always
    # ports:
    #   - 8080:8080
    depends_on:
      - mongodb

  angular-chat-webapp:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: angular_chat_webapp
    restart: always
    # ports:
    #   - 4200:4200
    depends_on:
      - mongodb

  angular-chat-nginx:
    build: 
      context: ./nginx/
      dockerfile: ./Dockerfile
    container_name: angular_chat_nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - angular-chat-webapp

